Hosp3/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.authentication.urls")),

    path("dashboard/", include("apps.dashboard.urls")),
    path("accounts/", include("apps.accounts.urls")),
    path("root/", include("apps.root.urls")),
    path("regi/", include("apps.regi.urls")),

    path("mate/", include("apps.mate.urls")),
    path("cons/", include("apps.cons.urls")),
    path("radi/", include("apps.radi.urls")),
    path("phar/", include("apps.phar.urls")),
    path("labo/", include("apps.labo.urls")),
    # path("ward/", include("apps.ward.urls")),

    # ----------- DRF URLS - APIs __________________________
    path("api/labo/", include("apps.labo.api_labo.urls")),
    path("api/radi/", include("apps.radi.api_radi.urls")),
    # path("api/mate/", include("apps.mate.api_mate.urls")),
    # path("api/ward/", include("apps.ward.api_ward.urls")),
    # path("api/phar/", include("apps.phar.api_phar.urls")),
]


'''
    path("api/regi/", include("apps.regi.api_regis.urls")),
    
    path("api/radio/", include("apps.radio.api_radi.urls")),
    path("api/pharm/", include("apps.pharm.api_pharm.urls")),
    path("api/ward", include("apps.ward.api_ward.urls")),

    # ----------- API TEST --------------------------
    path("api/", include("api.urls")),
    path("frontend/", include("frontend.urls")),
    '''

apps/labo/api_labo/urls.py
from django.urls import path, include
from .views import *
from .views1 import *
from .views2 import *
from rest_framework.routers import DefaultRouter

app_name = 'api_labo'

router = DefaultRouter
#router.register('lpatient', LaboPatViewSet, basename='lpatient')

urlpatterns = [

    # ======================= API CBV (api_labo\dviews.py) =====================
    # path('labpatlist/', LaboPatientList.as_view(), name='labpatlist'),
    # path('labpatdetail/<ln>/', LaboPatientDetail.as_view(), name='labpatdetail'),

    # path('labexamlistall/', LaboExamListAll.as_view(), name='labexamlistall'),
    # path('labexamlistone/<patient>', LaboExamListOne.as_view(), name='labexamlistone'),
    # path('labexamdetail/<id>', LaboExamDetail.as_view(), name='labexamdetail'),

    # path('labresultlistall/', LaboResultListAll.as_view(), name='labresultlistall'),
    # path('labresultlistall/<lexam>', LaboResultListOne.as_view(), name='labresultlistone'), # all results for 1 exam
    # path('labresultdetail/<id>', LaboResultDetail.as_view(), name='labresultdetail'),


    # ====================== API FBV (api_labo\views1.py) =======================
    # 1. No rest interface
    # path('labpatlist/', labo_patient_list, name='labpatlist'),
    # path('labpatdetail/<slug:ln>/', labo_patient_detail, name='labpatdetail'),

    # path('labexamlistall/', labo_exam_list_all, name='labexamlistall'),
    # path('labexamlistone/<slug:patient>', labo_exam_list_one, name='labexamlistone'),
    # path('labexamdetail/<int:id>', labo_exam_detail, name='labexamdetail'),

    # path('labresultlistall/', labo_result_list, name='labresultlistall'),
    # path('labresultlistone/<slug:lexam>', labo_result_list_one, name='labresultlistone'),
    # path('labresultdetail/<int:id>', labo_result_detail, name='labresultdetail'),

    # 2. With rest interface
    path('labpatlist/', labo_patient_list_1, name='labpatlist'),
    path('labpatdetail/<slug:ln>/', labo_patient_detail_1, name='labpatdetail'),

    path('labexamlistall/', labo_exam_list_all_1, name='labexamlistall'),
    path('labexamlistone/<slug:patient>', labo_exam_list_one_1, name='labexamlistone'),
    path('labexamdetail/<int:id>', labo_exam_detail, name='labexamdetail'),

    path('labresultlistall/', labo_result_list_1, name='labresultlistall'),
    path('labresultlistone/<slug:lexam>', labo_result_list_one_1, name='labresultlistone'),
    path('labresultdetail/<int:id>', labo_result_detail_1, name='labresultdetail'),


    # ================== API FBV (api_labo\views2.py) ===================
    # Using Mixins
    # path('generic/labopat/', GenericLaboPatAPIView.as_view(), name='labopat'),
    # path('generic/labopat/<slug:ln>/', GenericLaboPatAPIView.as_view(), name='labopat'),
    # path('generic/laboexam/', GenericLaboExamAPIView.as_view(), name='laboexam'),
    # path('generic/laboexam/<patient>', GenericLaboExamAPIView.as_view(), name='laboexam'),
    # path('generic/laboresult/', GenericLaboResultAPIView.as_view(), name='laboresult'),
    # path('generic/laboresult/<int:id>', GenericLaboResultAPIView.as_view(), name='laboresult'),

    # Using ViewSet and Routers
    # ====================== Using ViewSet =======================
    # path('viewset/', include(router.urls)),

]

apps/labo/urls.py
from django.urls import path
from . import apps
from . import views
from . import dviews
from . import search
from django.views.decorators.csrf import csrf_exempt

app_name = 'labo'

urlpatterns = [
    path('', views.laboWelcomeView, name='laboWelcome'),
    path('<int:id>', views.laboWelcomeView, name='laboWelcome'),
    path('laboHome/', views.laboHomeView, name='laboHome'),
    path('dash/', dviews.index, name='laboDash'),
    path('dash/page1', dviews.statistics, name='laboDash1'),
    path('dash/page2', dviews.income, name='laboDash2'),
    path('dash/page3', dviews.other, name='laboDash3'),

    # ======================== FBVs ==============================
    path('patcreate/', views.patient_create, name='laboPatCreate'),
    path('patlist/', views.patient_list, name='laboPatList'),
    path('patdetail/<slug>', views.patient_detail, name='laboPatDetail'),
    path('patupdate/', views.patient_update, name='laboPatUpdate'),
    path('patdelete/', views.patient_delete, name='laboPatDelete'),

    path('examcreate/', views.exam_create, name='laboExamCreate'),
    path('newtestinnewexam/', views.new_test_in_new_exam, name='newTestInNewExam'),
    path('examdetail/<slug>', views.exam_detail, name='laboExamDetail'),
    path('examupdate/<slug>', views.exam_detail, name='laboExamUpdate'),
    path('examlist/', views.exam_list, name='laboExamList'),

    path('examitemcreate/', views.exam_item_create, name='laboExamItemCreate'),
    # path('examitemdetail/<int:id>', views.exam_item_detail, name='laboExamItemdetail'),
    path('examitemupdate/<int:id>', views.exam_item_update, name='laboExamItemupdate'),

    path('resultcreate/', views.result_Create, name='laboResultCreate'),
    path('resultlist/', views.result_List, name='laboResultList'),
    path('resultdetail/<int:id>', views.result_Detail, name='laboResultDetail'),
    path('resultupdate/<slug:id>', views.result_Update, name='laboResultUpdate'),
    path('resultdelete/<slug:id>', views.result_Delete, name='laboResultDelete'),


    # ======================= Labo Staff ============================
    path('staffList/', views.staff_List, name='staffList'),
    path('staffCreate/', views.staff_Create, name='staffCreate'),
    path('staffUpdate/<int:id>', views.staff_Update, name='staffUpdate'),
    path('staffDelete/<int:id>', views.staff_Delete, name='staffDelete'),

    # ====================== Labo Category =========================
    path('categoryList/', views.category_List, name='categoryList'),
    path('categoryCreate/', views.category_Create, name='categoryCreate'),
    path('categoryUpdate/<int:id>', views.category_Update, name='categoryUpdate'),
    path('categoryDelete/<int:id>', views.category_Delete, name='categoryDelete'),

    # ====================== Labo Type =========================
    path('typeList/', views.type_List, name='typeList'),
    path('typeCreate/', views.type_Create, name='typeCreate'),
    path('typeUpdate/<int:id>', views.type_Update, name='typeUpdate'),
    path('typeDelete/<int:id>', views.type_Delete, name='typeDelete'),

    # ====================== Searches =========================
    path('search_labo_patient/', csrf_exempt(search.search_labo_patient), name='search_labo_patient'),  # by phone or ln
    path('search_labo_exam/', csrf_exempt(search.search_labo_exam), name='search_labo_exam'),  # by book_num or exam_num

    path('search_labo_test/', csrf_exempt(search.search_labo_test), name='search_labo_test'), # returns tests per category
    path('validate_code/', csrf_exempt(search.validate_code), name='validate_code'),

    # ==================== This year ========================
    path('labo_pats_this_year/', search.labo_pats_this_year, name='lP_all_this_Year'),
    path('labo_exams_this_year/', search.labo_exams_this_year, name='lE_all_this_Year'),
    path('labo_exams_item_this_year/', search.labo_exams_item_this_year, name='lEI_all_this_Year'),
    path('labo_tests_stats_this_year/', search.labo_tests_stats_this_year, name='lTS_this_Year'),

    # ==================== Last year ========================
    path('labo_pats_last_year/', search.labo_pats_last_year, name='lP_all_last_Year'),
    path('labo_exams_last_year/', search.labo_exams_last_year, name='lE_all_last_Year'),
    path('labo_exams_item_last_year/', search.labo_exams_item_last_year, name='lEI_all_last_Year'),

    # path('laboSearch1/', search_res_ln, name='laboSearch1'),
    # path('laboSearch2/', search_res_ph, name='laboSearch2'),
    # path('laboSearch3/', search_res_sn, name='laboSearch3'),
    # path('laboSearch4/', search_res_fn, name='laboSearch4'),
                 # returns tests per category
]

apps/labo/api_labo/forms.py
from django import forms

from apps.labo.models import LaboPatient, LaboExam, LaboResult


class LaboPatientForm(forms.ModelForm):
    class Meta:
        model = LaboPatient
        fields = "__all__"


class LaboExamForm(forms.ModelForm):
    class Meta:
        model = LaboExam
        fields = "__all__"


class LaboExamForm(forms.ModelForm):
    class Meta:
        model = LaboExam
        fields = "__all__"


class LaboResultForm(forms.ModelForm):
    class Meta:
        model = LaboResult
        fields = "__all__"

apps/labo/forms.py
from django import forms
from .models import *
from crispy_forms.helper import FormHelper
import datetime


class LaboPatientForm(forms.ModelForm):
    class Meta:
        model = LaboPatient
        fields = "__all__"


class LaboExamForm(forms.ModelForm):
    class Meta:
        model = LaboExam
        fields = "__all__"
        exclude = ["labo_type"]


class LaboExamItemForm(forms.ModelForm):
    class Meta:
        model = LaboExamItem
        fields = "__all__"


class LaboFindingForm(forms.ModelForm):
    class Meta:
        model = LaboFinding
        fields = "__all__"


class LaboTestCategoryForm(forms.ModelForm):
    class Meta:
        model = LaboTestCategory
        fields = "__all__"


class LaboTestTypeForm(forms.ModelForm):
    class Meta:
        model = LaboTestType
        fields = "__all__"


class LaboStaffForm(forms.ModelForm):
    class Meta:
        model = LaboStaff
        fields = "__all__"

apps/labo/api_labo/views.py
# from apps.labo.models import LaboPatient, LaboExam, LaboType
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated


from apps.labo.api_labo.serializers import *
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, generics, mixins, viewsets


# ================== API CBVs ======================
class LaboPatientList(APIView):
    def get(self, request, format=None):            # List Lab Patients
        lpatients = LaboPatient.objects.all()
        serializer = LaboPatientSerializer(lpatients, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):           # Create Lap Patients
        serializer = LaboPatientSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LaboPatientDetail(APIView):

    def get_object(self, ln):
        try:
            return LaboPatient.objects.get(ln=ln)
        except LaboPatient.DoesNotExist:
            #raise Http404
            return HttpResponse(status=status.HTTP_404_NOT_FOUND)

    def get(self, request, ln, format=None):
        lpatient = self.get_object(ln)
        serializer = LaboPatientSerializer(lpatient)
        return Response(serializer.data)

    def put(self, request, ln, format=None):
        lpatient = self.get_object(ln)
        serializer = LaboPatientSerializer(lpatient, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, ln, format=None):
        lpatient = self.get_object(ln)
        lpatient.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class LaboExamListAll(APIView):
    def get(self, request, format=None):            # List Lab Patients
        lexam = LaboExam.objects.all()
        serializer = LaboExamSerializer(lexam, many=True)
        return Response(serializer.data)


class LaboExamListOne(APIView):
    def get(self, request, patient, format=None):            # List Lab Patients
        lexams = LaboExam.objects.filter(patient=patient)
        serializer = LaboExamSerializer(lexams, many=True)
        return Response([serializer.data,])

    def post(self, request, format=None):           # Create Lap Exam
        serializer = LaboExamSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LaboExamDetail(APIView):

    def get_object(self, id):
        try:
            return LaboExam.objects.get(id=id)
        except LaboExam.DoesNotExist:
            raise Http404

    def get(self, request, id, format=None):
        lexam = self.get_object(id)
        serializer = LaboExamSerializer(lexam)
        return Response(serializer.data)

    def put(self, request, id, format=None):
        lexam = self.get_object(id)
        serializer = LaboExamSerializer(lexam, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, ys, format=None):
        lexam = self.get_object(ys)
        lexam.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class LaboResultListAll(APIView):
    def get(self, request, format=None):            # List Lab Patients
        lresult = LaboResult.objects.all()
        serializer = LaboResultSerializer(lresult, many=True)
        return Response(serializer.data)


class LaboResultListOne(APIView):
    def get(self, request, lexam, format=None):            # List Lab Patients
        lresult = LaboResult.objects.all()
        lresultone = lresult.filter(lexam=lexam)
        serializer = LaboResultSerializer(lresultone, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):           # Create Lap Patients
        serializer = LaboExamSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LaboResultDetail(APIView):

    def get_object(self, id):
        try:
            return LaboResult.objects.get(id=id)
        except LaboResult.DoesNotExist:
            raise Http404

    def get(self, request, id, format=None):
        lresultone = self.get_object(id)
        serializer = LaboResultSerializer(lresultone)
        return Response(serializer.data)

    def put(self, request, id, format=None):
        lexam = self.get_object(id)
        serializer = LaboExamSerializer(lexam, data=request.data)
        if serializer.is_valid():
            serializer.save()
            print("updated")
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, id, format=None):
        lexam = self.get_object(id)
        lexam.delete()
        print("deleted")
        return Response(status=status.HTTP_204_NO_CONTENT)

Hosp3/templates/labo/main2/category_create.html
{% load static %}
{% load crispy_forms_tags %}
<form method="post" data-url="{% url 'labo:categoryCreate' %}" action="" class="create-staff" autocomplete="off">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Create Category</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {{ category_form|crispy }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-success" id="submit-create-category"><i class="fas fa-database"></i>Submit</button>
    </div>
</form>

<script src="{% static 'labo/category_create.js' %}"></script>

Hosp3/templates/labo/main2/category_delete.html
{% load static %}
{% load crispy_forms_tags %}
<form method="post" data-url="{% url 'labo:categoryCreate' %}" action="" class="create-staff" autocomplete="off">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">DELETE CATEGORY DATA</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <h4><center> You Are About To Delete Staff With Info</center></h4>
        <label for="staff_name">CATEGORY Name</label>
            <input type="text" value={{ category_delete.category_name }} id="staff_name" readonly>
        <hr>
        <label for="category_id">ID</label>
            <input type="text" value={{ category_delete.id }} id="category_id" readonly>
    </div>
    <div class="modal-footer">
        <h6><center>Click out of this box To cancel</center></h6>
        <button type="button" class="btn btn-success" id="submit-delete-category"><i class="fas fa-database"></i>Delete</button>
    </div>
</form>

<script src="{% static 'labo/category_create.js' %}"></script>

Hosp3/templates/labo/main2/labo_category.html
{% extends 'labo/base_welcome_labo.html'%}
{% load static %}

{% block page_content %}

    <div class="container-fluid" id="forms">
      <div class="card card-body" id="category-form">
        <button class="btn btn-primary show-form">
          <span>Add Category</span>
        </button>
        <table class="table table-borderless">
          <thead class="border-bottom font-weight-bold">
            <tr>
              <td>ID</td>
              <td>CATEGORY NAME</td>
              <td>
                <a href="{% url 'labo:categoryCreate' %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg"></i>
                </a>
              </td>
              <td></td>
            <tr>
          </thead>
          <tbody>
          {% for category in labo_category %}
            <tr>
              <td>{{category.id}}</td>
              <td>{{category.category_name}}</td>

              <td>
                <button class="category-update">
                  <a href="" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg">Update</i>
                  </a>
                </button>
              </td>

              <td>
                <button class="category-delete">
                  <a href="" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg">Delete</i>
                  </a>
                </button>
              </td>

            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="modal" id="modal-category">
        <div class="modal-dialog">
          <div class="modal-content"></div>
          <h3>test</h3>
        </div>
      </div>
    </div>

{% endblock %}

{% block custom_js %}
    <script src="{% static 'labo/category_create.js' %}"></script>
{% endblock %}

Hosp3/templates/labo/main2/labo_category_form.html
{% extends 'labo/base_welcome_labo.html'%}
{% load static %}
{% load crispy_forms_tags %}

{% block page_content %}

    <div class="container-fluid" id="forms">
      <div class="card card-body" id="staff-form">
        <a href="{% url 'labo:categoryList' %}" class="btn text-secondary px-0">
          <i class="far fa-edit fa-lg">Category List</i>
        </a>
        <form action="" method="post" autocomplete="off">
          {% csrf_token %}
          {{ category_form|crispy }}
          <br>
          <button class="btn btn-success"><i class="fas fa-database"></i>Submit</button>
        </form>
      </div>
    </div>

{% endblock %}

Hosp3/templates/labo/main2/labo_dash_page2.html
{% extends 'labo/labo_base_dash.html' %}
{% load static %}

    {% block content %}

            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
             <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Dashboard</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{% url 'labo:laboHome' %}">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->

            <div class="container-fluid">
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                      <thead>
                                        <tr>
                                          <th>Month</th>
                                          <th>Header</th>
                                          <th>Header</th>
                                          <th>Header</th>
                                          <th>Header</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                          <td>1,001</td>
                                          <td>Lorem</td>
                                          <td>ipsum</td>
                                          <td>dolor</td>
                                          <td>sit</td>
                                        </tr>
                                        <tr>
                                          <td>1,002</td>
                                          <td>amet</td>
                                          <td>consectetur</td>
                                          <td>adipiscing</td>
                                          <td>elit</td>
                                        </tr>
                                        <tr>
                                          <td>1,002</td>
                                          <td>amet</td>
                                          <td>consectetur</td>
                                          <td>adipiscing</td>
                                          <td>elit</td>
                                        </tr>
                                      </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->

                <hr>

                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                      <thead>
                                        <tr>
                                          <th>Month</th>
                                          <th>Header</th>
                                          <th>Header</th>
                                          <th>Header</th>
                                          <th>Header</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                        <tr>
                                          <td>1,001</td>
                                          <td>Lorem</td>
                                          <td>ipsum</td>
                                          <td>dolor</td>
                                          <td>sit</td>
                                        </tr>
                                        <tr>
                                          <td>1,002</td>
                                          <td>amet</td>
                                          <td>consectetur</td>
                                          <td>adipiscing</td>
                                          <td>elit</td>
                                        </tr>
                                        <tr>
                                          <td>1,002</td>
                                          <td>amet</td>
                                          <td>consectetur</td>
                                          <td>adipiscing</td>
                                          <td>elit</td>
                                        </tr>
                                      </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->

            </div>

    {% endblock content %}

Hosp3/templates/labo/main2/labo_staff.html
{% extends 'labo/base_welcome_labo.html'%}
{% load static %}

{% block page_content %}

    <div class="container-fluid" id="forms">
      <div class="card card-body" id="staff-form">
        <button class="btn btn-primary show-form">
          <span>Add Staff</span>
        </button>
        <table class="table table-borderless">
          <thead class="border-bottom font-weight-bold">
            <tr>
              <td>ID</td>
              <td>FULL NAME</td>
              <td>PHONE</td>
              <td>ADDRESS</td>
              <td>TITLE</td>
              <td>
                <a href="{% url 'labo:staffCreate' %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg"></i>
                </a>
              </td>
              <td></td>
            <tr>
          </thead>
          <tbody>
          {% for staff in labo_staff%}
            <tr>
              <td>{{staff.id}}</td>
              <td>{{staff.full_name}}</td>
              <td>{{staff.Phone}}</td>
              <td>{{staff.address}}</td>
              <td>{{staff.title}}</td>

              <td>
                <button class="staff-update">
                  <a href="{% url 'labo:staffUpdate' staff.id %}" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg">Update</i>
                  </a>
                </button>
              </td>

              <td>
                <button class="staff-delete">
                  <a href="{% url 'labo:staffDelete' staff.id %}" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg">Delete</i>
                  </a>
                </button>
              </td>

            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="modal" id="modal-staff">
        <div class="modal-dialog">
          <div class="modal-content"></div>

        </div>
      </div>
    </div>

{% endblock %}

{% block custom_js %}
    <script src="{% static 'labo/staff_create.js' %}"></script>
{% endblock %}

Hosp3/templates/labo/main2/labo_type.html
{% extends 'labo/base_welcome_labo.html'%}
{% load static %}

{% block page_content %}

    <div class="container-fluid" id="forms">
      <div class="card card-body" id="type-form">
        <button class="btn btn-primary show-form">
          <span>Add Test Type</span>
        </button>
        <table class="table table-borderless">
          <thead class="border-bottom font-weight-bold">
            <tr>
              <td>ID</td>
              <td>TYPE NAME</td>
              <td>COST</td>
              <td>DEPARTMENT</td>
              <td>CATEGORY</td>
              <td>
                <a href="{% url 'labo:typeCreate' %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg"></i>
                </a>
              </td>
              <td></td>
            <tr>
          </thead>
          <tbody>
          {% for type in labo_type %}
            <tr>
              <td>{{type.id}}</td>
              <td>{{type.type_name}}</td>
              <td>{{type.cost}}</td>
              <td>{{type.department}}</td>
              <td>{{type.category}}</td>

              <td>
                <button class="type-update">
                  <a href="" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg">Update</i>
                  </a>
                </button>
              </td>

              <td>
                <button class="type-delete">
                  <a href="{% url 'labo:typeDelete' type.id %}" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg">Delete</i>
                  </a>
                </button>
              </td>

            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="modal" id="modal-type">
        <div class="modal-dialog">
          <div class="modal-content"></div>

        </div>
      </div>
    </div>

{% endblock %}

{% block custom_js %}
    <script src="{% static 'labo/type_create.js' %}"></script>
{% endblock %}