Hosp3/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.authentication.urls")),

    path("dashboard/", include("apps.dashboard.urls")),
    path("accounts/", include("apps.accounts.urls")),
    path("root/", include("apps.root.urls")),
    path("regi/", include("apps.regi.urls")),

    path("mate/", include("apps.mate.urls")),
    path("cons/", include("apps.cons.urls")),
    path("radi/", include("apps.radi.urls")),
    path("phar/", include("apps.phar.urls")),
    path("labo/", include("apps.labo.urls")),
    # path("ward/", include("apps.ward.urls")),

    # ----------- DRF URLS - APIs __________________________
    path("api/labo/", include("apps.labo.api_labo.urls")),
    path("api/radi/", include("apps.radi.api_radi.urls")),
    # path("api/mate/", include("apps.mate.api_mate.urls")),
    # path("api/ward/", include("apps.ward.api_ward.urls")),
    # path("api/phar/", include("apps.phar.api_phar.urls")),
]


'''
    path("api/regi/", include("apps.regi.api_regis.urls")),
    
    path("api/radio/", include("apps.radio.api_radi.urls")),
    path("api/pharm/", include("apps.pharm.api_pharm.urls")),
    path("api/ward", include("apps.ward.api_ward.urls")),

    # ----------- API TEST --------------------------
    path("api/", include("api.urls")),
    path("frontend/", include("frontend.urls")),
    '''

apps/labo/api_labo/urls.py
from django.urls import path, include
from .views import *
from .views1 import *
from .views2 import *
from rest_framework.routers import DefaultRouter

app_name = 'api_labo'

router = DefaultRouter
#router.register('lpatient', LaboPatViewSet, basename='lpatient')

urlpatterns = [

    # ======================= API CBV (api_labo\dviews.py) =====================
    # path('labpatlist/', LaboPatientList.as_view(), name='labpatlist'),
    # path('labpatdetail/<ln>/', LaboPatientDetail.as_view(), name='labpatdetail'),

    # path('labexamlistall/', LaboExamListAll.as_view(), name='labexamlistall'),
    # path('labexamlistone/<patient>', LaboExamListOne.as_view(), name='labexamlistone'),
    # path('labexamdetail/<id>', LaboExamDetail.as_view(), name='labexamdetail'),

    # path('labresultlistall/', LaboResultListAll.as_view(), name='labresultlistall'),
    # path('labresultlistall/<lexam>', LaboResultListOne.as_view(), name='labresultlistone'), # all results for 1 exam
    # path('labresultdetail/<id>', LaboResultDetail.as_view(), name='labresultdetail'),


    # ====================== API FBV (api_labo\views1.py) =======================
    # 1. No rest interface
    # path('labpatlist/', labo_patient_list, name='labpatlist'),
    # path('labpatdetail/<slug:ln>/', labo_patient_detail, name='labpatdetail'),

    # path('labexamlistall/', labo_exam_list_all, name='labexamlistall'),
    # path('labexamlistone/<slug:patient>', labo_exam_list_one, name='labexamlistone'),
    # path('labexamdetail/<int:id>', labo_exam_detail, name='labexamdetail'),

    # path('labresultlistall/', labo_result_list, name='labresultlistall'),
    # path('labresultlistone/<slug:lexam>', labo_result_list_one, name='labresultlistone'),
    # path('labresultdetail/<int:id>', labo_result_detail, name='labresultdetail'),

    # 2. With rest interface
    path('labpatlist/', labo_patient_list_1, name='labpatlist'),
    path('labpatdetail/<slug:ln>/', labo_patient_detail_1, name='labpatdetail'),

    path('labexamlistall/', labo_exam_list_all_1, name='labexamlistall'),
    path('labexamlistone/<slug:patient>', labo_exam_list_one_1, name='labexamlistone'),
    path('labexamdetail/<int:id>', labo_exam_detail, name='labexamdetail'),

    path('labresultlistall/', labo_result_list_1, name='labresultlistall'),
    path('labresultlistone/<slug:lexam>', labo_result_list_one_1, name='labresultlistone'),
    path('labresultdetail/<int:id>', labo_result_detail_1, name='labresultdetail'),


    # ================== API FBV (api_labo\views2.py) ===================
    # Using Mixins
    # path('generic/labopat/', GenericLaboPatAPIView.as_view(), name='labopat'),
    # path('generic/labopat/<slug:ln>/', GenericLaboPatAPIView.as_view(), name='labopat'),
    # path('generic/laboexam/', GenericLaboExamAPIView.as_view(), name='laboexam'),
    # path('generic/laboexam/<patient>', GenericLaboExamAPIView.as_view(), name='laboexam'),
    # path('generic/laboresult/', GenericLaboResultAPIView.as_view(), name='laboresult'),
    # path('generic/laboresult/<int:id>', GenericLaboResultAPIView.as_view(), name='laboresult'),

    # Using ViewSet and Routers
    # ====================== Using ViewSet =======================
    # path('viewset/', include(router.urls)),

]

apps/labo/urls.py
from django.urls import path
from . import apps
from . import views
from . import dviews
from . import search
from django.views.decorators.csrf import csrf_exempt

app_name = 'labo'

urlpatterns = [
    path('', views.laboWelcomeView, name='laboWelcome'),
    path('<int:id>', views.laboWelcomeView, name='laboWelcome'),
    path('laboHome/', views.laboHomeView, name='laboHome'),
    path('dash/', dviews.index, name='laboDash'),
    path('dash/page1', dviews.statistics, name='laboDash1'),
    path('dash/page2', dviews.income, name='laboDash2'),
    path('dash/page3', dviews.other, name='laboDash3'),

    # ======================== FBVs ==============================
    path('patcreate/', views.patient_create, name='laboPatCreate'),
    path('patlist/', views.patient_list, name='laboPatList'),
    path('patdetail/<slug>', views.patient_detail, name='laboPatDetail'),
    path('patupdate/', views.patient_update, name='laboPatUpdate'),
    path('patdelete/', views.patient_delete, name='laboPatDelete'),

    path('examcreate/', views.exam_create, name='laboExamCreate'),
    path('newtestinnewexam/', views.new_test_in_new_exam, name='newTestInNewExam'),
    path('examdetail/<slug>', views.exam_detail, name='laboExamDetail'),
    path('examupdate/<slug>', views.exam_detail, name='laboExamUpdate'),
    path('examlist/', views.exam_list, name='laboExamList'),

    path('examitemcreate/', views.exam_item_create, name='laboExamItemCreate'),
    # path('examitemdetail/<int:id>', views.exam_item_detail, name='laboExamItemdetail'),
    path('examitemupdate/<int:id>', views.exam_item_update, name='laboExamItemupdate'),

    path('resultcreate/', views.result_Create, name='laboResultCreate'),
    path('resultlist/', views.result_List, name='laboResultList'),
    path('resultdetail/<int:id>', views.result_Detail, name='laboResultDetail'),
    path('resultupdate/<slug:id>', views.result_Update, name='laboResultUpdate'),
    path('resultdelete/<slug:id>', views.result_Delete, name='laboResultDelete'),


    # ======================= Labo Staff ============================
    path('staffList/', views.staff_List, name='staffList'),
    path('staffCreate/', views.staff_Create, name='staffCreate'),
    path('staffUpdate/<int:id>', views.staff_Update, name='staffUpdate'),
    path('staffDelete/<int:id>', views.staff_Delete, name='staffDelete'),

    # ====================== Labo Category =========================
    path('categoryList/', views.category_List, name='categoryList'),
    path('categoryCreate/', views.category_Create, name='categoryCreate'),
    path('categoryUpdate/<int:id>', views.category_Update, name='categoryUpdate'),
    path('categoryDelete/<int:id>', views.category_Delete, name='categoryDelete'),

    # ====================== Labo Type =========================
    path('typeList/', views.type_List, name='typeList'),
    path('typeCreate/', views.type_Create, name='typeCreate'),
    path('typeUpdate/<int:id>', views.type_Update, name='typeUpdate'),
    path('typeDelete/<int:id>', views.type_Delete, name='typeDelete'),

    # ====================== Searches =========================
    path('search_labo_patient/', csrf_exempt(search.search_labo_patient), name='search_labo_patient'),  # by phone or ln
    path('search_labo_exam/', csrf_exempt(search.search_labo_exam), name='search_labo_exam'),  # by book_num or exam_num

    path('search_labo_test/', csrf_exempt(search.search_labo_test), name='search_labo_test'), # returns tests per category
    path('validate_code/', csrf_exempt(search.validate_code), name='validate_code'),

    # ==================== This year ========================
    path('labo_pats_this_year/', search.labo_pats_this_year, name='lP_all_this_Year'),
    path('labo_exams_this_year/', search.labo_exams_this_year, name='lE_all_this_Year'),
    path('labo_exams_item_this_year/', search.labo_exams_item_this_year, name='lEI_all_this_Year'),
    path('labo_tests_stats_this_year/', search.labo_tests_stats_this_year, name='lTS_this_Year'),

    # ==================== Last year ========================
    path('labo_pats_last_year/', search.labo_pats_last_year, name='lP_all_last_Year'),
    path('labo_exams_last_year/', search.labo_exams_last_year, name='lE_all_last_Year'),
    path('labo_exams_item_last_year/', search.labo_exams_item_last_year, name='lEI_all_last_Year'),

    # path('laboSearch1/', search_res_ln, name='laboSearch1'),
    # path('laboSearch2/', search_res_ph, name='laboSearch2'),
    # path('laboSearch3/', search_res_sn, name='laboSearch3'),
    # path('laboSearch4/', search_res_fn, name='laboSearch4'),
                 # returns tests per category
]

apps/regi/urls.py
from django.urls import path
from . import apps, views, search
from .views import *
from django.views.decorators.csrf import csrf_exempt


app_name = 'regi'

urlpatterns = [
    path('', regiWelcomeView, name='regiWelcome'),
    path('regHome/', regiRegistration, name='regHome'),
    path('payHome/', regiPayment, name='payHome'),

    path('regiCreate/', patient_Create, name='regiPatCreate'),
    path('regiList/', patient_List, name='regiPatList'),
    path('regiUpdate/<int:id>/', patient_Update, name='regiUpdate'),
    path('regiDelete/<int:id>/', patient_Delete, name='regiDelete'),

    path('patCreateModalU/', patient_Create_Modal_u, name='PatCreateModalU'),
    path('patUpdate/<int:sn>', patient_update, name='patUpdate'),
    path('patCreateModalX/', patient_Create_Modal_x, name='PatCreateModalX'),
    path('patSearch/', csrf_exempt(views.patSearch), name='patSearch'),

    # ======================= Regis Staff ============================
    path('staffList/', views.staff_List, name='staffList'),
    path('staffCreate/', views.staff_Create, name='staffCreate'),
    path('staffUpdate/<int:id>', views.staff_Update, name='staffUpdate'),
    path('staffDelete/<int:id>', views.staff_Delete, name='staffDelete'),

    path('search_patient/', csrf_exempt(search.search_patient), name='search_patient'),  # by phone or sn

]

apps/labo/api_labo/forms.py
from django import forms

from apps.labo.models import LaboPatient, LaboExam, LaboResult


class LaboPatientForm(forms.ModelForm):
    class Meta:
        model = LaboPatient
        fields = "__all__"


class LaboExamForm(forms.ModelForm):
    class Meta:
        model = LaboExam
        fields = "__all__"


class LaboExamForm(forms.ModelForm):
    class Meta:
        model = LaboExam
        fields = "__all__"


class LaboResultForm(forms.ModelForm):
    class Meta:
        model = LaboResult
        fields = "__all__"

apps/labo/forms.py
from django import forms
from .models import *
from crispy_forms.helper import FormHelper
import datetime


class LaboPatientForm(forms.ModelForm):
    class Meta:
        model = LaboPatient
        fields = "__all__"


class LaboExamForm(forms.ModelForm):
    class Meta:
        model = LaboExam
        fields = "__all__"
        exclude = ["labo_type"]


class LaboExamItemForm(forms.ModelForm):
    class Meta:
        model = LaboExamItem
        fields = "__all__"


class LaboFindingForm(forms.ModelForm):
    class Meta:
        model = LaboFinding
        fields = "__all__"


class LaboTestCategoryForm(forms.ModelForm):
    class Meta:
        model = LaboTestCategory
        fields = "__all__"


class LaboTestTypeForm(forms.ModelForm):
    class Meta:
        model = LaboTestType
        fields = "__all__"


class LaboStaffForm(forms.ModelForm):
    class Meta:
        model = LaboStaff
        fields = "__all__"

apps/regi/forms.py
from django import forms
from django.forms import NumberInput

from .models import *
import datetime


class RegPatientForm(forms.ModelForm):
    reg_num = forms.CharField(max_length=5, widget=forms.TextInput(attrs={'id': 'id_reg_num_reg', 'style': 'width:8ch'}))
    reg_num2 = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'id': 'id_reg_num_reg2', 'hidden': 'hidden'}), label='')
    first_name = forms.CharField(max_length=12, widget=forms.TextInput(attrs={'id': 'id_first_name_reg'}))
    last_name = forms.CharField(max_length=12, required=False, widget=forms.TextInput(attrs={'id': 'id_last_name_reg'}))
    full_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly', 'hidden': 'hidden'}),
                                initial='full name', required=False, label='')
    address = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'id': 'id_address_reg'}))
    # sex = forms.CharField(attrs={'id': 'id_sex'})
    dob = forms.DateField(widget=NumberInput(attrs={'type': 'date', 'id': 'id_dob_reg'}))
    age = forms.CharField(widget=forms.TextInput(attrs={'id': 'id_age_reg', 'readonly': 'readonly'}),
                          initial="", required=False, label='')      # 'hidden': 'hidden'})
    Phone = forms.CharField(max_length=9, required=False, widget=forms.TextInput(attrs={'id': 'id_phone_reg'}))

    class Meta:
        model = Patient
        fields = ['reg_num', 'first_name', 'last_name', 'address', 'sex', 'dob', 'age', 'Phone', 'full_name']


class RegiStaffForm(forms.ModelForm):
    class Meta:
        model = RegiStaff
        fields = "__all__"

Hosp3/templates/regi/main2/labo_category.html
{% extends 'labo/base_welcome_labo.html'%}
{% load static %}

{% block page_content %}

    <div class="container-fluid" id="forms">
      <div class="card card-body" id="staff-form">
        <table class="table table-borderless">
          <thead class="border-bottom font-weight-bold">
            <tr>
              <td>ID</td>
              <td>CATEGORY NAME</td>
              <td>
                <a href="{% url 'labo:categoryCreate' %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg">Add Category</i>
                </a>
              </td>
              <td></td>
            <tr>
          </thead>
          <tbody>
          {% for category in labo_category %}
            <tr>
              <td>{{category.id}}</td>
              <td>{{category.category_name}}</td>
              <td>
                <a href="{% url 'labo:categoryUpdate' category.id %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg">Update</i>
                </a>
              </td>
              <td>
                <a href="{% url 'labo:categoryDelete' category.id %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg">Delete</i>
                </a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

{% endblock %}

Hosp3/templates/regi/main2/labo_category_form.html
{% extends 'labo/base_welcome_labo.html'%}
{% load static %}
{% load crispy_forms_tags %}

{% block page_content %}

    <div class="container-fluid" id="forms">
      <div class="card card-body" id="staff-form">
        <a href="{% url 'labo:categoryList' %}" class="btn text-secondary px-0">
          <i class="far fa-edit fa-lg">Category List</i>
        </a>
        <form action="" method="post" autocomplete="off">
          {% csrf_token %}
          {{ category_form|crispy }}
          <br>
          <button class="btn btn-success"><i class="fas fa-database"></i>Submit</button>
        </form>
      </div>
    </div>

{% endblock %}

Hosp3/templates/regi/main2/labo_type.html
{% extends 'labo/base_welcome_labo.html'%}
{% load static %}

{% block page_content %}

    <div class="container-fluid" id="forms">
      <div class="card card-body" id="staff-form">
        <table class="table table-borderless">
          <thead class="border-bottom font-weight-bold">
            <tr>
              <td>ID</td>
              <td>TYPE NAME</td>
              <td>FEES</td>
              <td>CATEGORY</td>
              <td>
                <a href="{% url 'labo:typeCreate' %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg">Add Exam Type</i>
                </a>
              </td>
              <td></td>
            <tr>
          </thead>
          <tbody>
          {% for type in labo_type %}
            <tr>
              <td>{{type.id}}</td>
              <td>{{type.type_name}}</td>
              <td>{{type.fees}}</td>
              <td>{{type.category}}</td>
              <td>
                <a href="{% url 'labo:typeUpdate' type.id %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg">Update</i>
                </a>
              </td>
              <td>
                <a href="{% url 'labo:typeDelete' type.id %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg">Delete</i>
                </a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

{% endblock %}

Hosp3/templates/regi/main2/labo_type_form.html
{% extends 'labo/base_welcome_labo.html'%}
{% load static %}
{% load crispy_forms_tags %}

{% block page_content %}

    <div class="container-fluid" id="forms">
      <div class="card card-body" id="staff-form">
        <a href="{% url 'labo:typeList' %}" class="btn text-secondary px-0">
          <i class="far fa-edit fa-lg">Exam Type List</i>
        </a>
        <form action="" method="post" autocomplete="off">
          {% csrf_token %}
          {{ type_form|crispy }}
          <br>
          <button class="btn btn-success"><i class="fas fa-database"></i>Submit</button>
        </form>
      </div>
    </div>

{% endblock %}

Hosp3/templates/regi/main2/modal_pat_create.html
{% load static %}
{% load crispy_forms_tags %}
<form method="post" data-url="" action="" class="create-pat" autocomplete="off">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Create Patient</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form method="post" action="" id="patient-form" class="form-horizontal">
             {% csrf_token %}
            <div class="card-body">
                <h4 class="card-title">Fill Patient Info</h4>
                <div class="form-group row">
                    <label for="id_reg_num" class="col-sm-3 text-right control-label col-form-label">Register Number</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="id_reg_num" placeholder="Book-Num">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_first_name" class="col-sm-3 text-right control-label col-form-label">First Name</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="id_first_name" maxlength="12" placeholder="">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_last_name" class="col-sm-3 text-right control-label col-form-label">Last Name</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="id_last_name" maxlength="12" placeholder="">
                    </div>
                </div>
                <div class="form-group row" hidden>
                    <label for="id_full_name" class="col-sm-3 text-right control-label col-form-label">Full Name</label>
                    <div class="col-sm-9">
                        <input type="text" value="N/A" class="form-control" id="id_full_name" placeholder="" readonly>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_address1" class="col-sm-3 text-right control-label col-form-label">Address</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="id_address1" maxlength="15" placeholder="">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_sex" class="col-sm-3 text-right control-label col-form-label">Sex</label>
                    <div class="col-sm-9">
                        <select type="text" class="form-control" id="id_sex" placeholder="MALE or FEMALE">
                            <option value=""></option>
                            <option value="MALE">MALE</option>
                            <option value="FEMALE">FEMALE</option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_dob" class="col-sm-3 text-right control-label col-form-label">Date of Birth</label>
                    <div class="col-sm-9">
                        <input type="date" class="form-control" id="id_dob" placeholder="1990-12-31">
                    </div>
                </div>
                <div class="form-group row" hidden>
                    <label for="id_age" class="col-sm-3 text-right control-label col-form-label">Age</label>
                    <div class="col-sm-9">
                        <input type="text" value="Input DOB" class="form-control" id="id_age" placeholder="" readonly>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_Phone" class="col-sm-3 text-right control-label col-form-label">Phone</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="id_Phone" maxlength="9" minlength="9" placeholder="67xxxxxxxx">
                    </div>
                </div>

                <div class="border-top modal-footer">
                    <div class="card-body">
                        <button type="submit" id="submit-modal-create-pat" class="btn btn-primary"><i class="fas fa-database"></i>Register Patient</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</form>

<script src="{% static 'radi/radi_upat_create.js' %}"></script>

Hosp3/templates/regi/main2/patient_update.html
{% extends "radi/ubase.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}
    <style xmlns="http://www.w3.org/1999/html">
    </style>
{% endblock %}
{% block page_title %}
 Form
{% endblock %}
{% block content %}
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">{{ sub_title }}</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'radi:radiWelcome' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Register Results</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">


    <!-- PATIENT INFO CARD -->
    <div class="col-md-12">
        <div class="card">
            <form method="post" action="" id="patient-form" class="form-horizontal">
                 {% csrf_token %}
                <div class="card-body">
                    <h4 class="card-title">Update Patient</h4>
                    <hr>
                    <div class="row">
                        <div id="div_id_sn" class="form-group col">
                            <label for="id_sn" class=" requiredField">Serial Number</label>
                            <input type="text" class="form-control" id="id_sn" value={{ form.sn}} readonly>
                        </div>

                        <div id="div_id_reg_num" class="form-group col">
                            <label for="id_reg_num" class=" requiredField">Registration Number</label>
                            <input type="text" class="form-control" id="id_reg_num" value={{ form.reg_num}} readonly>
                        </div>
                    </div>

                    <div class="row">
                        <div id="div_id_first_name" class="form-group col-md-4">
                            <label for="id_first_name" class=" requiredField">First Name</label>
                            <input type="text" class="form-control" id="id_first_name" value={{ form.first_name}}>
                        </div>
                        <div id="div_id_last_name" class="form-group col-md-4">
                            <label for="id_last_name" class=" requiredField">Last Name</label>
                            <input type="text" class="form-control" id="id_last_name" value={{ form.last_name}}>
                        </div>
                        <div id="div_id_full_name" class="form-group col-md-4">
                            <label for="id_full_name" class=" requiredField">Full Name</label>
                            <input type="text" class="form-control" id="id_full_name" value={{ form.full_name}} readonly>
                        </div>
                    </div>
                    <div class="row">
                        <div id="div_id_sex" class="form-group col-md-6">
                            <label for="id_sex" class=" requiredField">Sex</label>
                            <select name=sex id="id_sex" class="form-control">
                                <option selected value={{ form.sex }}>{{ form.sex }}</option>
                                <option value="MALE">MALE</option>
                                <option value="FEMALE">FEMALE</option>
                            </select>
                        </div>
                        <div id="div_id_address" class="form-group col-md-6">
                            <label for="id_address" class=" requiredField">Address</label>
                            <input type="text" class="form-control" id="id_address" value={{ form.address}}>
                        </div>
                    </div>
                    <div class="row">
                        <div id="div_id_phone" class="form-group col">
                            <label for="id_phone" class=" requiredField">Phone</label>
                            <input type="text" class="form-control" id="id_phone" value={{ form.phone}}>
                        </div>
                        <div id="div_id_dob" class="form-group col">
                            <label for="id_dob" class=" requiredField">Date Of Birth</label>
                            <input type="date" class="form-control" id="id_dob" value={{ form.dob }}>
                        </div>
                    </div>
                    <hr>

                    <div class="card-body">
                        <button type="submit" id="submit-update-patient" class="btn btn-primary">Update Patient</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

        </div>
    </div>


{% endblock %}

{% block extra_script %}
    <script src="{% static 'radi/radi_upat_create.js' %}" defer></script>
{% endblock %}

Hosp3/templates/regi/main2/regi_staff.html
{% extends 'regi/base_welcome_regi.html'%}
{% load static %}

{% block page_content %}

    <div class="container-fluid" id="forms">
      <div class="card card-body" id="staff-form">
        <button class="btn btn-primary show-form">
          <span>Add Staff</span>
        </button>
        <table class="table table-borderless">
          <thead class="border-bottom font-weight-bold">
            <tr>
              <td>ID</td>
              <td>FULL NAME</td>
              <td>PHONE</td>
              <td>ADDRESS</td>
              <td>TITLE</td>
              <td>
                <a href="{% url 'regi:staffCreate' %}" class="btn text-secondary px-0">
                  <i class="far fa-edit fa-lg"></i>
                </a>
              </td>
              <td></td>
            <tr>
          </thead>
          <tbody>
          {% for staff in regi_staff%}
            <tr>
              <td>{{staff.id}}</td>
              <td>{{staff.full_name}}</td>
              <td>{{staff.Phone}}</td>
              <td>{{staff.address}}</td>
              <td>{{staff.title}}</td>

              <td>
                <button class="staff-update">
                  <a href="{% url 'regi:staffUpdate' staff.id %}" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg">Update</i>
                  </a>
                </button>
              </td>

              <td>
                <button class="staff-delete">
                  <a href="{% url 'regi:staffDelete' staff.id %}" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg">Delete</i>
                  </a>
                </button>
              </td>

            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="modal" id="modal-staff">
        <div class="modal-dialog">
          <div class="modal-content"></div>
          <h3>test</h3>
        </div>
      </div>
    </div>

{% endblock %}

{% block custom_js %}
    <script src="{% static 'regi/staff_create.js' %}"></script>
{% endblock %}