Hosp3/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.authentication.urls")),

    path("dashboard/", include("apps.dashboard.urls")),
    path("accounts/", include("apps.accounts.urls")),
    path("root/", include("apps.root.urls")),
    path("regi/", include("apps.regi.urls")),

    path("mate/", include("apps.mate.urls")),
    path("cons/", include("apps.cons.urls")),
    path("radi/", include("apps.radi.urls")),
    path("phar/", include("apps.phar.urls")),
    path("labo/", include("apps.labo.urls")),
    # path("ward/", include("apps.ward.urls")),

    # ----------- DRF URLS - APIs __________________________
    path("api/labo/", include("apps.labo.api_labo.urls")),
    path("api/radi/", include("apps.radi.api_radi.urls")),
    # path("api/mate/", include("apps.mate.api_mate.urls")),
    # path("api/ward/", include("apps.ward.api_ward.urls")),
    # path("api/phar/", include("apps.phar.api_phar.urls")),
]


'''
    path("api/regi/", include("apps.regi.api_regis.urls")),
    
    path("api/radio/", include("apps.radio.api_radi.urls")),
    path("api/pharm/", include("apps.pharm.api_pharm.urls")),
    path("api/ward", include("apps.ward.api_ward.urls")),

    # ----------- API TEST --------------------------
    path("api/", include("api.urls")),
    path("frontend/", include("frontend.urls")),
    '''

apps/radi/api_radi/urls.py
from django.urls import path
from .views import *            # PatientListAPIView

app_name = 'api_radi'

urlpatterns = [
    # ___________________ ECHO API URLs ___________________________________
    path('upatlist/', UPatientList.as_view(), name='upatlist'),
    path('upatdetail/<un>/', UPatientDetail.as_view(), name='upatpetail'),

    path('uexamlistall/', UExamListAll.as_view(), name='uexamlistall'),
    path('uexamlistall/<patient>', UExamListOne.as_view(), name='uexamlistone'),
    path('uexamdetail/<ys>', UExamDetail.as_view(), name='uexamdetail'),

    path('uresultlistall/', UResultListAll.as_view(), name='uresultlistall'),
    path('uresultlistall/<lexam>', UResultListOne.as_view(), name='uresultlistone'), # all results for 1 exam
    path('uresultdetail/<id>', UResultDetail.as_view(), name='uresultdetail'),

    # path('uspatdelete/<un>/', UPatientDelete.as_view(), name='uspatdelete'),

    # ___________________ XRAY API URLs ___________________________________
    path('xpatlist/', XPatientList.as_view(), name='xpatlist'),
    path('xpatdetail/<xn>/', XPatientDetail.as_view(), name='xpatpetail'),

    path('xexamlistall/', XExamListAll.as_view(), name='xexamlistall'),
    path('xexamlistall/<patient>', XExamListOne.as_view(), name='xexamlistone'),
    path('xexamdetail/<ys>', XExamDetail.as_view(), name='xexamdetail'),

    path('xresultlistall/', XResultListAll.as_view(), name='xresultlistall'),
    path('xresultlistall/<lexam>', XResultListOne.as_view(), name='xresultlistone'),  # all results for 1 exam
    path('xresultdetail/<id>', XResultDetail.as_view(), name='xresultdetail'),

]

apps/radi/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import apps
from . import views
from . import dviews
from . import uviews
from . import xviews
from . import usearch
from . import xsearch
from . import print

app_name = 'radi'

urlpatterns = [
    path('', views.radiWelcomeView, name='radiWelcome'),

    path('udash/', dviews.u_index, name='echoDash'),
    path('udash/page0', dviews.u_statistics_0, name='echoDash0'),
    path('udash/page1', dviews.u_statistics_1, name='echoDash1'),
    path('udash/page2', dviews.u_statistics_2, name='echoDash2'),
    path('udash/page3', dviews.u_income, name='echoDash3'),
    path('udash/page4', dviews.u_other, name='echoDash4'),

    path('xdash/', dviews.x_index, name='xrayDash'),
    path('xdash/page1', dviews.x_statistics_1, name='xrayDash1'),
    path('xdash/page2', dviews.x_statistics_2, name='xrayDash2'),
    path('xdash/page3', dviews.x_income, name='xrayDash3'),
    path('xdash/page4', dviews.x_other, name='xrayDash4'),


    # ======================= Radio Staff ============================
    path('staffList/', views.staff_List, name='staffList'),
    path('staffCreate/', views.staff_Create, name='staffCreate'),
    path('staffUpdate/<int:id>', views.staff_Update, name='staffUpdate'),
    path('staffDelete/<int:id>', views.staff_Delete, name='staffDelete'),

    # ====================== Radio Category =========================
    path('categoryList/', views.category_List, name='categoryList'),
    path('categoryCreate/', views.category_Create, name='categoryCreate'),
    path('categoryUpdate/<int:id>', views.category_Update, name='categoryUpdate'),
    path('categoryDelete/<int:id>', views.category_Delete, name='categoryDelete'),

    # ====================== Radi Exam Type =========================
    path('typeList/', views.type_List, name='typeList'),
    path('typeCreate/', views.type_Create, name='typeCreate'),
    path('typeUpdate/<int:id>', views.type_Update, name='typeUpdate'),
    path('typeDelete/<int:id>', views.type_Delete, name='typeDelete'),

    # ====================== Radi Department =========================
    path('deptList/', views.dept_List, name='deptList'),
    path('deptCreate/', views.dept_Create, name='deptCreate'),
    path('deptUpdate/<int:id>', views.dept_Update, name='deptUpdate'),
    # path('deptDelete/<int:id>', views.dept_Delete, name='deptDelete'),

    # ====================== Radi Handing Over =========================
    path('handingList/', views.handing_List, name='handingList'),
    path('handingCreate/', views.handing_Create, name='handingCreate'),
    path('handingUpdate/<int:id>', views.handing_Update, name='handingUpdate'),
    path('handingDelete/<int:id>', views.handing_Delete, name='handingDelete'),

    # ======================== Maintence ===========================
    path('maintenanceList/', views.maintenance_List, name='maintenanceList'),
    path('maintenanceCreate/', views.maintenance_Create, name='maintenanceCreate'),
    path('maintenanceUpdate/<int:id>', views.maintenance_Update, name='maintenanceUpdate'),
    path('maintenanceDelete/<int:id>', views.maintenance_Delete, name='maintenanceDelete'),

    # ======================== Echo Views ==============================
    path('echo/', uviews.echoHomeView, name='echoHomeView'),
    path('u_patcreate/', uviews.u_patient_create, name='echoPatCreate'),
    path('u_patlist/', uviews.u_patient_list, name='echoPatList'),
    path('u_patdetail/<slug>', uviews.u_patient_detail, name='echoPatDetail'),
    path('u_patdelete/', uviews.u_patient_delete, name='echoPatDelete'),
    path('u_examcreate/', uviews.u_exam_create, name='echoExamCreate'),
    path('u_examlist/', uviews.u_exam_list, name='echoExamList'),
    path('u_examdetail/<slug:slug>', uviews.u_exam_detail, name='echoExamDetail'),
    path('u_examupdate/<slug:slug>', uviews.u_exam_update, name='echoExamUpdate'),
    path('u_examitemcreate/', uviews.u_exam_item_create, name='echoExamItemCreate'),
    path('u_examitemlist/', uviews.u_exam_item_list, name='echoExamItemList'),
    path('u_examitemlistall/', uviews.u_exam_item_list_all, name='echoExamItemListAll'),
    path('u_examitemupdate/<int:id>', uviews.u_exam_item_update, name='echoExamItemUpdate'),
    path('u_resultcreate/', uviews.u_result_create, name='echoResultCreate'),
    path('u_resultlist/', uviews.u_result_list, name='echoResultList'),
    path('u_resultlistall/', uviews.u_result_list_all, name='echoResultListAll'),
    path('u_resultdetail/<int:id>', uviews.u_result_detail, name='echoResultDetail'),
    path('u_resultupdate/<int:id>', uviews.u_result_update, name='echoResultUpdate'),


    # ======================== Radio Views ==============================
    path('xray/', xviews.xrayHomeView, name='xrayHomeView'),
    path('x_patcreate/', xviews.x_patient_create, name='xrayPatCreate'),
    path('x_patlist/', xviews.x_patient_list, name='xrayPatList'),
    path('x_patdetail/<slug>', xviews.x_patient_detail, name='xrayPatDetail'),
    path('x_patdelete/', xviews.x_patient_delete, name='xrayPatDelete'),
    path('x_examcreate/', xviews.x_exam_create, name='xrayExamCreate'),
    path('x_examlist/', xviews.x_exam_list, name='xrayExamList'),
    path('x_examitemcreate/', xviews.x_exam_item_create, name='xrayExamItemCreate'),
    path('x_examitemlist/', xviews.x_exam_item_list, name='xrayExamItemList'),
    path('x_resultcreate/', xviews.x_result_create, name='xrayResultCreate'),
    path('x_resultlist/', xviews.x_result_list, name='xrayResultList'),
    path('x_resultdetail/<int:id>', xviews.x_result_detail, name='xrayResultDetail'),
    path('x_resultupdate/<int:id>', xviews.x_result_update, name='xrayResultUpdate'),

    # Echo Patient CRUD
    path('echoPatientCreate/', uviews.u_patient_create, name='echoPatientCreate'),  # get and post req. Create
    path('echoPatientList/', uviews.u_patient_list, name='echoPatientList'),        # get and post req. Retrieve and Display
    path('echoPatientDelete/<slug:un>/', uviews.u_patient_delete, name='echoPatientDelete'),   # get and post req. Delete
    path('echoPatientDetail/<slug:un>/', uviews.u_patient_detail, name='echoPatientDetail'),

    # ==================== ECHO SEARCHES ===================================================
    path('search_echo_test/', csrf_exempt(usearch.search_echo_test), name='search_echo_test'),
    path('search_echo_exam/', csrf_exempt(usearch.search_echo_exam), name='search_echo_exam'),
    path('search_patient/', csrf_exempt(usearch.search_patient), name='search_patient'),  # by phone or sn

    # ==================== XRAY SEARCHES ===================================================
    path('search_xray_test/', csrf_exempt(xsearch.search_xray_test), name='search_xray_test'),
    path('searchxray_exam/', csrf_exempt(xsearch.search_xray_exam), name='search_xray_exam'),
    path('search_patient/', csrf_exempt(usearch.search_patient), name='search_patient'),  # by phone or sn

    # ==================== ECHO STATISTICS ========================
    path('echo_exams_stats_0_this_month/', usearch.echo_exams_stats_0_this_month, name='ES_this_month'),
    path('echo_pats_chart_1_this_year/', usearch.echo_pats_chart_1_this_year, name='RUTS_this_1_Year'),
    path('echo_exams_chart_1_this_year/', usearch.echo_exams_chart_1_this_year, name='RUTS_this_1_Year'),
    path('echo_tests_stats_1_this_year/', usearch.echo_tests_stats_1_this_year, name='RUTS_this_1_Year'),
    path('echo_tests_stats_2_this_year/', usearch.echo_tests_stats_2_this_year, name='RUTS_this_2_Year'),

    # =================== NOTIFICATIONS ==========================
    path('notification_items/', usearch.notification_items, name='notification'),
    path('patNoExam/', usearch.pat_with_no_exam, name='PWNE_this_1_Year'),
    path('examNoTest/', usearch.exam_with_no_test, name='EWNT_this_1_Year'),
    path('obSexMale/', usearch.echo_exam_ob_male, name='OESM_this_1_Year'),
    path('skippedNumThis/', usearch.echo_skipped_number_this, name='ESN_this'),

    # ==================== XRAY STATISTICS ========================
    path('xray_pats_chart_1_this_year/', xsearch.xray_pats_chart_1_this_year, name='RXTS_this_1_Year'),
    # path('xray_pats_chart_1_this_year/', xsearch.xray_pats_chart_1_this_year, name='RXTS_this_1_Year'),

    path('xray_exams_chart_1_this_year/', xsearch.xray_exams_chart_1_this_year, name='RXTS_this_1_Year'),
    # path('xray_exams_chart_1_this_year/', xsearch.xray_exams_chart_1_this_year, name='RUTS_this_1_Year'),

    path('xray_tests_stats_1_this_year/', xsearch.xray_tests_stats_1_this_year, name='RXTS_this_1_Year'),
    path('xray_tests_stats_2_this_year/', xsearch.xray_tests_stats_2_this_year, name='RXTS_this_2_Year'),

    path('search_echo_patient/', csrf_exempt(usearch.search_echo_patient), name='search_echo_patient'),  # returns tests per category
    path('search_echo_exam/', csrf_exempt(usearch.search_echo_exam), name='search_echo_exam'),  # returns echo exams
    path('all_test_for_exam/<slug:book_num>/', usearch.all_test_for_exam, name='all_test_for_exam'),  # returns echo exams
    path('search_xray_patient/', csrf_exempt(xsearch.search_xray_patient), name='search_xray_patient'),  # returns tests per category
    path('validate_code/', csrf_exempt(usearch.validate_code), name='validate_code'),  # returns tests per category

    path('patCreateModalDetailU/<slug:book_num>/', views.patient_Create_Modal_Detail_u, name='PatCreateModalDetailU'),
    path('resCreateDetailModalU/', uviews.result_create_confirm_u, name='result_create_confirm_u'),

    path('checkRegNum/', csrf_exempt(usearch.check_regnum_exist), name='search_reg_num'),  # by phone or sn
    path('checkBookNum/', csrf_exempt(usearch.check_book_num_exist), name='search_book_num'),  # by phone or sn
    path('checkFullName/', csrf_exempt(usearch.check_full_name_exist), name='search_full_name'),  #

apps/regi/urls.py
from django.urls import path
from . import apps, views, search
from .views import *
from django.views.decorators.csrf import csrf_exempt


app_name = 'regi'

urlpatterns = [
    path('', regiWelcomeView, name='regiWelcome'),
    path('regHome/', regiRegistration, name='regHome'),
    path('payHome/', regiPayment, name='payHome'),

    path('regiCreate/', patient_Create, name='regiPatCreate'),
    path('regiList/', patient_List, name='regiPatList'),
    path('regiUpdate/<int:id>/', patient_Update, name='regiUpdate'),
    path('regiDelete/<int:id>/', patient_Delete, name='regiDelete'),

    path('patCreateModalU/', patient_Create_Modal_u, name='PatCreateModalU'),
    path('patUpdate/<int:sn>', patient_update, name='patUpdate'),
    path('patCreateModalX/', patient_Create_Modal_x, name='PatCreateModalX'),
    path('patSearch/', csrf_exempt(views.patSearch), name='patSearch'),

    # ======================= Regis Staff ============================
    path('staffList/', views.staff_List, name='staffList'),
    path('staffCreate/', views.staff_Create, name='staffCreate'),
    path('staffUpdate/<int:id>', views.staff_Update, name='staffUpdate'),
    path('staffDelete/<int:id>', views.staff_Delete, name='staffDelete'),

    path('search_patient/', csrf_exempt(search.search_patient), name='search_patient'),  # by phone or sn

]

apps/radi/forms.py
from django import forms
from django.forms import NumberInput

from .models import *


class RadiDeptForm(forms.ModelForm):
    class Meta:
        model = RadiDept
        fields = "__all__"


class RadiStaffForm(forms.ModelForm):
    first_name = forms.CharField(max_length=10)
    last_name = forms.CharField(max_length=10, required=False)
    full_name = forms.CharField(widget=forms.TextInput(
        attrs={'hidden': 'hidden', 'readonly': 'readonly'}), label='', required=False)
    address = forms.CharField(max_length=15)
    dob = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))
    age = forms.CharField(widget=forms.TextInput(
        attrs={'hidden': 'hidden', 'readonly': 'readonly'}), label='', initial=0, required=False)
    Phone = forms.CharField(max_length=9)


    class Meta:
        model = RadiStaff
        fields = "__all__"


class RadiTestCategoryForm(forms.ModelForm):
    class Meta:
        model = RadiTestCategory
        fields = "__all__"


class RadiTypeForm(forms.ModelForm):
    class Meta:
        model = RadiTestType
        fields = "__all__"


class RadiHandingForm(forms.ModelForm):
    class Meta:
        model = RadiHanding
        fields = "__all__"


class UPatientForm(forms.ModelForm):
    class Meta:
        model = UPatient
        fields = "__all__"


class XPatientForm(forms.ModelForm):
    class Meta:
        model = XPatient
        fields = "__all__"


class UExamForm(forms.ModelForm):
    class Meta:
        model = UExam
        fields = "__all__"
        exclude = ["u_exam"]


class XExamForm(forms.ModelForm):
    class Meta:
        model = XExam
        fields = "__all__"
        exclude = ["x_exam"]


class UExamItemForm(forms.ModelForm):
    class Meta:
        model = UExamItem
        fields = "__all__"


SIDES = [('None', 'N/A'), ('Right', 'Right'), ('Left', 'Left')]
POSITION = [('None', 'N/A'), ('PA', 'PA'), ('AP', 'AP'), ('oblique', 'oblique')]


class XExamItemForm(forms.ModelForm):
    side = forms.ChoiceField(choices=SIDES)
    position = forms.ChoiceField(choices=POSITION)
    class Meta:
        model = XExamItem
        fields = "__all__"


class UFindingForm(forms.ModelForm):
    class Meta:
        model = UFinding
        fields = "__all__"


class XFindingForm(forms.ModelForm):
    class Meta:
        model = XFinding
        fields = "__all__"

Hosp3/templates/radi/echo/echo_pat_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Hosp3/templates/radi/echo/echo_pat_list.html
{% extends "radi/ubase.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    <style xmlns="http://www.w3.org/1999/html">
    </style>
{% endblock %}
{% block page_title %}
 Tables
{% endblock %}

{% block extra_style %}
<link href="{% static 'dashboard/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet"/>
{% endblock extra_style %}

{% block content %}

    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">{{ sub_title }}</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'radi:radiWelcome' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">List</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ page_title }} PATIENT LIST</h5>
                        <div class="table-responsive">
                            <table id="zero_config" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>US #</th>
                                    <th>SN</th>
                                    <th>Full Name</th>
                                    <th>Age</th>
                                    <th>Sex</th>
                                    <th>Phone</th>
                                    <th>Address</th>
                                    <th>Date Created</th>
                                    <th>Edit</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for pat in pats %}
                                    <tr>
                                      <td><a href="{% url 'radi:echoPatDetail' pat.un %}"><b><h5>{{ pat.un }}</h5></b></a></td>
                                      <td>{{ pat.patient.sn }}</td>
                                      <td>{{ pat.patient.full_name }}</td>
                                      <td>{{ pat.patient.age }}</td>
                                      <td>{{ pat.patient.sex }}</td>
                                      <td>{{ pat.patient.Phone }}</td>
                                      <td>{{ pat.patient.address }}</td>
                                      <td>{{ pat.date_created.date }}</td>
                                      <td class="">
                                          <a href="{% url 'regi:patUpdate' pat.sn %}" class="btn btn-secondary p-1">
                                              <i class="far fa-edit fa-sm"></i>
                                          </a>
                                      </td>
                                    </tr>
                                  {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

{% block extra_script %}
<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>
<script>
    $(document).ready(function () {
        $('#zero_config').DataTable();
    });
</script>
<script src="{% static 'dashboard/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'dashboard/js/datatables.min.js' %}"></script>

{% endblock %}

Hosp3/templates/radi/echo/radi_upat_create.html
{% extends "radi/base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    <style xmlns="http://www.w3.org/1999/html">
    </style>
{% endblock %}
{% block page_title %}
 Form
{% endblock %}
{% block content %}
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">{{ sub_title }}</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'radi:radiWelcome' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Register Patient</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">

                    </div>
                </div>
            </div>
            <!--SEARCH PATIENT CARD-->
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <!--<h5 class="card-title col-md-12">Search Patient</h5>-->
                            <!--Search by-->
                            <div class="form-group col-md-5">
                                <label><h5>Search By</h5></label>
                                    <select class="form-control" type="text" name="query-select" id="query-type">
                                        <!--<option value="">---------</option>-->
                                        <option value="Phone">Phone Number</option>
                                        <option value="sn">Patient SN</option>
                                    </select>
                            </div>
                            <!--Query-->
                            <div class="form-group col-md-7">
                                <form id="search-form" autocomplete="off">
                                    {% csrf_token %}
                                    <label for="Search Patient"><h5>Enter Query</h5></label>
                                    <input id="search-input" placeholder="" class="form-control" type="text">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- SEARCH RESULT CARD -->
            <div class="col-12 not-visible" id="result-box">
                <div class="col-12"><center><h5>RESULTS</h5></center></div>
                <div class="table-responsive" id="table-output">
                    <table id="" class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>Serial #</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Age</th>
                            <th>Sex</th>
                            <th>Phone</th>
                            <th>Phone</th>
                            <th>Date Created</th>
                        </tr>
                        </thead>
                        <tbody id="table-body">

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- PATIENT INFO CARD -->
            <div class="col-md-12">
                <div class="card">
                    <form method="post" action="" id="patient-form" class="form-horizontal">
                         {% csrf_token %}
                        <div class="card-body">
                            <h4 class="card-title">Patient Info</h4>
                            <div class="form-group row">
                                <label for="sn" class="col-sm-3 text-right control-label col-form-label">Serial Number</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="id_sn" placeholder="" readonly>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="full_name" class="col-sm-3 text-right control-label col-form-label">Full Name</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="id_fullname" placeholder="" readonly>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="address" class="col-sm-3 text-right control-label col-form-label">Address</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="id_address" placeholder="" readonly>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="age" class="col-sm-3 text-right control-label col-form-label">Age</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="id_age" placeholder="" readonly>
                                </div>
                            </div>

                        <div class="border-top">
                            <div class="card-body">
                                <button type="submit" id="submit-form" class="btn btn-primary">Register Patient</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>

        </div>
    </div>


{% endblock %}

{% block extra_script %}
    <script>
            //***********************************//
            // For select 2
            //***********************************//
            $(".select2").select2();

            /*colorpicker*/
            $('.demo').each(function () {
                $(this).minicolors({
                    control: $(this).attr('data-control') || 'hue',
                    position: $(this).attr('data-position') || 'bottom left',

                    change: function (value, opacity) {
                        if (!value) return;
                        if (opacity) value += ', ' + opacity;
                        if (typeof console === 'object') {
                            console.log(value);
                        }
                    },
                    theme: 'bootstrap'
                });

            });
            /*datwpicker*/
            jQuery('.mydatepicker').datepicker();
            jQuery('#datepicker-autoclose').datepicker({
                autoclose: true,
                todayHighlight: true
            });

            var quill = new Quill('#editor', {
                theme: 'snow'
            });
        </script>
    <script src="{% static 'radi/radi_upat_create.js' %}" defer></script>
{% endblock %}

Hosp3/templates/radi/echo/radi_upat_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>