Hosp3/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.authentication.urls")),

    path("dashboard/", include("apps.dashboard.urls")),
    path("accounts/", include("apps.accounts.urls")),
    path("root/", include("apps.root.urls")),
    path("regi/", include("apps.regi.urls")),

    path("mate/", include("apps.mate.urls")),
    path("cons/", include("apps.cons.urls")),
    path("radi/", include("apps.radi.urls")),
    path("phar/", include("apps.phar.urls")),
    path("labo/", include("apps.labo.urls")),
    # path("ward/", include("apps.ward.urls")),

    # ----------- DRF URLS - APIs __________________________
    path("api/labo/", include("apps.labo.api_labo.urls")),
    path("api/radi/", include("apps.radi.api_radi.urls")),
    # path("api/mate/", include("apps.mate.api_mate.urls")),
    # path("api/ward/", include("apps.ward.api_ward.urls")),
    # path("api/phar/", include("apps.phar.api_phar.urls")),
]


'''
    path("api/regi/", include("apps.regi.api_regis.urls")),
    
    path("api/radio/", include("apps.radio.api_radi.urls")),
    path("api/pharm/", include("apps.pharm.api_pharm.urls")),
    path("api/ward", include("apps.ward.api_ward.urls")),

    # ----------- API TEST --------------------------
    path("api/", include("api.urls")),
    path("frontend/", include("frontend.urls")),
    '''

apps/labo/api_labo/urls.py
from django.urls import path, include
from .views import *
from .views1 import *
from .views2 import *
from rest_framework.routers import DefaultRouter

app_name = 'api_labo'

router = DefaultRouter
#router.register('lpatient', LaboPatViewSet, basename='lpatient')

urlpatterns = [

    # ======================= API CBV (api_labo\dviews.py) =====================
    # path('labpatlist/', LaboPatientList.as_view(), name='labpatlist'),
    # path('labpatdetail/<ln>/', LaboPatientDetail.as_view(), name='labpatdetail'),

    # path('labexamlistall/', LaboExamListAll.as_view(), name='labexamlistall'),
    # path('labexamlistone/<patient>', LaboExamListOne.as_view(), name='labexamlistone'),
    # path('labexamdetail/<id>', LaboExamDetail.as_view(), name='labexamdetail'),

    # path('labresultlistall/', LaboResultListAll.as_view(), name='labresultlistall'),
    # path('labresultlistall/<lexam>', LaboResultListOne.as_view(), name='labresultlistone'), # all results for 1 exam
    # path('labresultdetail/<id>', LaboResultDetail.as_view(), name='labresultdetail'),


    # ====================== API FBV (api_labo\views1.py) =======================
    # 1. No rest interface
    # path('labpatlist/', labo_patient_list, name='labpatlist'),
    # path('labpatdetail/<slug:ln>/', labo_patient_detail, name='labpatdetail'),

    # path('labexamlistall/', labo_exam_list_all, name='labexamlistall'),
    # path('labexamlistone/<slug:patient>', labo_exam_list_one, name='labexamlistone'),
    # path('labexamdetail/<int:id>', labo_exam_detail, name='labexamdetail'),

    # path('labresultlistall/', labo_result_list, name='labresultlistall'),
    # path('labresultlistone/<slug:lexam>', labo_result_list_one, name='labresultlistone'),
    # path('labresultdetail/<int:id>', labo_result_detail, name='labresultdetail'),

    # 2. With rest interface
    path('labpatlist/', labo_patient_list_1, name='labpatlist'),
    path('labpatdetail/<slug:ln>/', labo_patient_detail_1, name='labpatdetail'),

    path('labexamlistall/', labo_exam_list_all_1, name='labexamlistall'),
    path('labexamlistone/<slug:patient>', labo_exam_list_one_1, name='labexamlistone'),
    path('labexamdetail/<int:id>', labo_exam_detail, name='labexamdetail'),

    path('labresultlistall/', labo_result_list_1, name='labresultlistall'),
    path('labresultlistone/<slug:lexam>', labo_result_list_one_1, name='labresultlistone'),
    path('labresultdetail/<int:id>', labo_result_detail_1, name='labresultdetail'),


    # ================== API FBV (api_labo\views2.py) ===================
    # Using Mixins
    # path('generic/labopat/', GenericLaboPatAPIView.as_view(), name='labopat'),
    # path('generic/labopat/<slug:ln>/', GenericLaboPatAPIView.as_view(), name='labopat'),
    # path('generic/laboexam/', GenericLaboExamAPIView.as_view(), name='laboexam'),
    # path('generic/laboexam/<patient>', GenericLaboExamAPIView.as_view(), name='laboexam'),
    # path('generic/laboresult/', GenericLaboResultAPIView.as_view(), name='laboresult'),
    # path('generic/laboresult/<int:id>', GenericLaboResultAPIView.as_view(), name='laboresult'),

    # Using ViewSet and Routers
    # ====================== Using ViewSet =======================
    # path('viewset/', include(router.urls)),

]

apps/labo/urls.py
from django.urls import path
from . import apps
from . import views
from . import dviews
from . import search
from django.views.decorators.csrf import csrf_exempt

app_name = 'labo'

urlpatterns = [
    path('', views.laboWelcomeView, name='laboWelcome'),
    path('<int:id>', views.laboWelcomeView, name='laboWelcome'),
    path('laboHome/', views.laboHomeView, name='laboHome'),
    path('dash/', dviews.index, name='laboDash'),
    path('dash/page1', dviews.statistics, name='laboDash1'),
    path('dash/page2', dviews.income, name='laboDash2'),
    path('dash/page3', dviews.other, name='laboDash3'),

    # ======================== FBVs ==============================
    path('patcreate/', views.patient_create, name='laboPatCreate'),
    path('patlist/', views.patient_list, name='laboPatList'),
    path('patdetail/<slug>', views.patient_detail, name='laboPatDetail'),
    path('patupdate/', views.patient_update, name='laboPatUpdate'),
    path('patdelete/', views.patient_delete, name='laboPatDelete'),

    path('examcreate/', views.exam_create, name='laboExamCreate'),
    path('newtestinnewexam/', views.new_test_in_new_exam, name='newTestInNewExam'),
    path('examdetail/<slug>', views.exam_detail, name='laboExamDetail'),
    path('examupdate/<slug>', views.exam_detail, name='laboExamUpdate'),
    path('examlist/', views.exam_list, name='laboExamList'),

    path('examitemcreate/', views.exam_item_create, name='laboExamItemCreate'),
    # path('examitemdetail/<int:id>', views.exam_item_detail, name='laboExamItemdetail'),
    path('examitemupdate/<int:id>', views.exam_item_update, name='laboExamItemupdate'),

    path('resultcreate/', views.result_Create, name='laboResultCreate'),
    path('resultlist/', views.result_List, name='laboResultList'),
    path('resultdetail/<int:id>', views.result_Detail, name='laboResultDetail'),
    path('resultupdate/<slug:id>', views.result_Update, name='laboResultUpdate'),
    path('resultdelete/<slug:id>', views.result_Delete, name='laboResultDelete'),


    # ======================= Labo Staff ============================
    path('staffList/', views.staff_List, name='staffList'),
    path('staffCreate/', views.staff_Create, name='staffCreate'),
    path('staffUpdate/<int:id>', views.staff_Update, name='staffUpdate'),
    path('staffDelete/<int:id>', views.staff_Delete, name='staffDelete'),

    # ====================== Labo Category =========================
    path('categoryList/', views.category_List, name='categoryList'),
    path('categoryCreate/', views.category_Create, name='categoryCreate'),
    path('categoryUpdate/<int:id>', views.category_Update, name='categoryUpdate'),
    path('categoryDelete/<int:id>', views.category_Delete, name='categoryDelete'),

    # ====================== Labo Type =========================
    path('typeList/', views.type_List, name='typeList'),
    path('typeCreate/', views.type_Create, name='typeCreate'),
    path('typeUpdate/<int:id>', views.type_Update, name='typeUpdate'),
    path('typeDelete/<int:id>', views.type_Delete, name='typeDelete'),

    # ====================== Searches =========================
    path('search_labo_patient/', csrf_exempt(search.search_labo_patient), name='search_labo_patient'),  # by phone or ln
    path('search_labo_exam/', csrf_exempt(search.search_labo_exam), name='search_labo_exam'),  # by book_num or exam_num

    path('search_labo_test/', csrf_exempt(search.search_labo_test), name='search_labo_test'), # returns tests per category
    path('validate_code/', csrf_exempt(search.validate_code), name='validate_code'),

    # ==================== This year ========================
    path('labo_pats_this_year/', search.labo_pats_this_year, name='lP_all_this_Year'),
    path('labo_exams_this_year/', search.labo_exams_this_year, name='lE_all_this_Year'),
    path('labo_exams_item_this_year/', search.labo_exams_item_this_year, name='lEI_all_this_Year'),
    path('labo_tests_stats_this_year/', search.labo_tests_stats_this_year, name='lTS_this_Year'),

    # ==================== Last year ========================
    path('labo_pats_last_year/', search.labo_pats_last_year, name='lP_all_last_Year'),
    path('labo_exams_last_year/', search.labo_exams_last_year, name='lE_all_last_Year'),
    path('labo_exams_item_last_year/', search.labo_exams_item_last_year, name='lEI_all_last_Year'),

    # path('laboSearch1/', search_res_ln, name='laboSearch1'),
    # path('laboSearch2/', search_res_ph, name='laboSearch2'),
    # path('laboSearch3/', search_res_sn, name='laboSearch3'),
    # path('laboSearch4/', search_res_fn, name='laboSearch4'),
                 # returns tests per category
]

apps/labo/api_labo/forms.py
from django import forms

from apps.labo.models import LaboPatient, LaboExam, LaboResult


class LaboPatientForm(forms.ModelForm):
    class Meta:
        model = LaboPatient
        fields = "__all__"


class LaboExamForm(forms.ModelForm):
    class Meta:
        model = LaboExam
        fields = "__all__"


class LaboExamForm(forms.ModelForm):
    class Meta:
        model = LaboExam
        fields = "__all__"


class LaboResultForm(forms.ModelForm):
    class Meta:
        model = LaboResult
        fields = "__all__"

apps/labo/forms.py
from django import forms
from .models import *
from crispy_forms.helper import FormHelper
import datetime


class LaboPatientForm(forms.ModelForm):
    class Meta:
        model = LaboPatient
        fields = "__all__"


class LaboExamForm(forms.ModelForm):
    class Meta:
        model = LaboExam
        fields = "__all__"
        exclude = ["labo_type"]


class LaboExamItemForm(forms.ModelForm):
    class Meta:
        model = LaboExamItem
        fields = "__all__"


class LaboFindingForm(forms.ModelForm):
    class Meta:
        model = LaboFinding
        fields = "__all__"


class LaboTestCategoryForm(forms.ModelForm):
    class Meta:
        model = LaboTestCategory
        fields = "__all__"


class LaboTestTypeForm(forms.ModelForm):
    class Meta:
        model = LaboTestType
        fields = "__all__"


class LaboStaffForm(forms.ModelForm):
    class Meta:
        model = LaboStaff
        fields = "__all__"

apps/labo/api_labo/views.py
# from apps.labo.models import LaboPatient, LaboExam, LaboType
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated


from apps.labo.api_labo.serializers import *
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, generics, mixins, viewsets


# ================== API CBVs ======================
class LaboPatientList(APIView):
    def get(self, request, format=None):            # List Lab Patients
        lpatients = LaboPatient.objects.all()
        serializer = LaboPatientSerializer(lpatients, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):           # Create Lap Patients
        serializer = LaboPatientSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LaboPatientDetail(APIView):

    def get_object(self, ln):
        try:
            return LaboPatient.objects.get(ln=ln)
        except LaboPatient.DoesNotExist:
            #raise Http404
            return HttpResponse(status=status.HTTP_404_NOT_FOUND)

    def get(self, request, ln, format=None):
        lpatient = self.get_object(ln)
        serializer = LaboPatientSerializer(lpatient)
        return Response(serializer.data)

    def put(self, request, ln, format=None):
        lpatient = self.get_object(ln)
        serializer = LaboPatientSerializer(lpatient, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, ln, format=None):
        lpatient = self.get_object(ln)
        lpatient.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class LaboExamListAll(APIView):
    def get(self, request, format=None):            # List Lab Patients
        lexam = LaboExam.objects.all()
        serializer = LaboExamSerializer(lexam, many=True)
        return Response(serializer.data)


class LaboExamListOne(APIView):
    def get(self, request, patient, format=None):            # List Lab Patients
        lexams = LaboExam.objects.filter(patient=patient)
        serializer = LaboExamSerializer(lexams, many=True)
        return Response([serializer.data,])

    def post(self, request, format=None):           # Create Lap Exam
        serializer = LaboExamSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LaboExamDetail(APIView):

    def get_object(self, id):
        try:
            return LaboExam.objects.get(id=id)
        except LaboExam.DoesNotExist:
            raise Http404

    def get(self, request, id, format=None):
        lexam = self.get_object(id)
        serializer = LaboExamSerializer(lexam)
        return Response(serializer.data)

    def put(self, request, id, format=None):
        lexam = self.get_object(id)
        serializer = LaboExamSerializer(lexam, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, ys, format=None):
        lexam = self.get_object(ys)
        lexam.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class LaboResultListAll(APIView):
    def get(self, request, format=None):            # List Lab Patients
        lresult = LaboResult.objects.all()
        serializer = LaboResultSerializer(lresult, many=True)
        return Response(serializer.data)


class LaboResultListOne(APIView):
    def get(self, request, lexam, format=None):            # List Lab Patients
        lresult = LaboResult.objects.all()
        lresultone = lresult.filter(lexam=lexam)
        serializer = LaboResultSerializer(lresultone, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):           # Create Lap Patients
        serializer = LaboExamSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LaboResultDetail(APIView):

    def get_object(self, id):
        try:
            return LaboResult.objects.get(id=id)
        except LaboResult.DoesNotExist:
            raise Http404

    def get(self, request, id, format=None):
        lresultone = self.get_object(id)
        serializer = LaboResultSerializer(lresultone)
        return Response(serializer.data)

    def put(self, request, id, format=None):
        lexam = self.get_object(id)
        serializer = LaboExamSerializer(lexam, data=request.data)
        if serializer.is_valid():
            serializer.save()
            print("updated")
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, id, format=None):
        lexam = self.get_object(id)
        lexam.delete()
        print("deleted")
        return Response(status=status.HTTP_204_NO_CONTENT)

Hosp3/templates/labo/includes/footer.html
{% load static %}
  <footer class="footer text-center">
                All Rights Reserved by Nkwain-admin. Designed and Developed by <a href="https://wrappixel.com">Nkwain</a>.
  </footer>

Hosp3/templates/labo/includes/header.html
{% load static %}

 <header class="topbar" data-navbarbg="skin5">
    <nav class="navbar fixed-top top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin5">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="index.html">
                <!-- Logo icon -->
                <b class="logo-icon p-l-10">
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <h3>{{ page_title }}</h3>

                </b>

                <!--End Logo icon -->
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-left mr-auto">
                <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                <!-- ============================================================== -->
                <!-- create new -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     <span class="d-none d-md-block">Create New <i class="fa fa-angle-down"></i></span>
                     <span class="d-block d-md-none"><i class="fa fa-plus"></i></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
                <li class="nav-item search-box"> <a class="nav-link waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                    <form class="app-search position-absolute">
                        <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                    </form>
                </li>
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-right">
                <!-- ============================================================== -->
                <!-- Comment -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="mdi mdi-bell font-24"></i>
                    </a>
                     <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="font-24 mdi mdi-comment-processing"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right mailbox animated bounceInDown" aria-labelledby="2">
                        <ul class="list-style-none">
                            <li>
                                <div class="">
                                     <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-success btn-circle"><i class="ti-calendar"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Event today</h5>
                                                <span class="mail-desc">Just a reminder that event</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-info btn-circle"><i class="ti-settings"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Settings</h5>
                                                <span class="mail-desc">You can customize this template</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-primary btn-circle"><i class="ti-user"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Pavan kumar</h5>
                                                <span class="mail-desc">Just see the my admin!</span>
                                            </div>
                                        </div>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="link border-top">
                                        <div class="d-flex no-block align-items-center p-10">
                                            <span class="btn btn-danger btn-circle"><i class="fa fa-link"></i></span>
                                            <div class="m-l-10">
                                                <h5 class="m-b-0">Luanch Admin</h5>
                                                <span class="mail-desc">Just see the my new admin!</span>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Messages -->
                <!-- ============================================================== -->

                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{% static 'images/users/1.jpg' %}" alt="user" class="rounded-circle" width="31"></a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated">
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-user m-r-5 m-l-5"></i> My Profile</a>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-wallet m-r-5 m-l-5"></i> My Balance</a>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-email m-r-5 m-l-5"></i> Inbox</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="ti-settings m-r-5 m-l-5"></i> Account Setting</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="javascript:void(0)"><i class="fa fa-power-off m-r-5 m-l-5"></i> Logout</a>
                        <div class="dropdown-divider"></div>
                        <div class="p-l-30 p-10"><a href="javascript:void(0)" class="btn btn-sm btn-success btn-rounded">View Profile</a></div>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>

Hosp3/templates/labo/includes/sidebar.html
{% load static %}

  <aside class="left-sidebar scrollable ps-container ps-theme-default ps-active-y" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'labo:laboDash' %}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                        <hr>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'labo:laboPatCreate' %}" aria-expanded="false"><i class="mdi mdi-chart-bar"></i><span class="hide-menu">New Patient</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'labo:laboExamCreate' %}" aria-expanded="false"><i class="mdi mdi-chart-bubble"></i><span class="hide-menu">New Exam</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'labo:laboExamItemCreate' %}" aria-expanded="false"><i class="mdi mdi-chart-bubble"></i><span class="hide-menu">New Lab Test</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'labo:laboResultCreate' %}" aria-expanded="false"><i class="mdi mdi-chart-bubble"></i><span class="hide-menu">Enter Results</span></a></li>
                        <hr>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'labo:laboPatList' %}" aria-expanded="false"><i class="mdi mdi-border-inside"></i><span class="hide-menu">Patient List</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'labo:laboExamList' %}" aria-expanded="false"><i class="mdi mdi-blur-linear"></i><span class="hide-menu">Exam List</span></a></li>
                        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'labo:laboResultList' %}" aria-expanded="false"><i class="mdi mdi-blur-linear"></i><span class="hide-menu">Result List</span></a></li>
                        <hr>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>